<a href="https://colab.research.google.com/github/PramodPatil16a/Pytorch-for-AI/blob/main/1_Tensors_in_Python_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors in pytorch

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not availabe. Using CPU")

GPU is available
using GPU: Tesla T4


Creating a Tensor

In [ ]:
#using empty (it will create a empty tensor) it will allocate a memory
a = torch.empty(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#check type - it will retun a type of tensor
type(a)

torch.Tensor

In [ ]:
#using zeros - used to create a size of tensor as per your wish to sart biaes vales as zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand - for wieght initilazation
torch.rand(2,3)

tensor([[0.3672, 0.2413, 0.7050],
        [0.0077, 0.4184, 0.4793]])

In [ ]:
#using of seed
torch.rand(2,3)

tensor([[0.4948, 0.4730, 0.4814],
        [0.3518, 0.8448, 0.7304]])

In [ ]:
# so if you use rand funtion every time you run u may get different output between 0 to 1 as it is a random funtion so each time you run you need a same output for rand then use seed funtion my calling it manually
#manual seed
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor - custom tensors you can create (you can give list tuple etc)
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

#arange - to provide a range
print("using arange: ", torch.arange(0,10,2))

using arange:  tensor([0, 2, 4, 6, 8])


In [ ]:
#using linspace (linearly space from range 0 to 10 , 10 evenly spaced values)
print("using linspace: ",torch.linspace(0,10,10))

using linspace:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
#using eye - for idenity matrics (means daigonal values are 1 rest all 0)
print("using eye: ",torch.eye(5))

using eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
#using full - ( will give size(3,3) and every item should be of same number eg:5 )
print("using full : ",torch.full((3,3),5))

using full :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[135526939766160,       857234784,       857033248],
        [      857302240,               0,       816431344]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# torch.rand_like(x) # it will not run by this code bcoz  we defined int so we have to define

torch.rand_like(x,dtype=torch.float32)



tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor Datatypes

In [ ]:
# to find dataType
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


Mathematical operations

1.scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
#addition
x + 2

#substracton
x - 2

#multiplication
x * 2

#division
x / 2

#int division
(x *100)/3

#mod
((x *100)/3)%2

#power
x**2




tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

2.element wise operations

In [ ]:
a = torch.rand(2,2)
b = torch.rand(2,2)

print(a)
print(b)

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])
tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)

tensor([[1.1753, 1.5804],
        [0.7796, 1.2794]])
tensor([[ 0.8185, -0.0673],
        [-0.3319, -0.6747]])
tensor([[0.1779, 0.6232],
        [0.1244, 0.2954]])
tensor([[5.5873, 0.9183],
        [0.4029, 0.3095]])
tensor([[0.9994, 0.7946],
        [0.4353, 0.3108]])
tensor([[0.1048, 0.7565],
        [0.2239, 0.3023]])


In [ ]:
#more
c = torch.tensor([1,-2,3,-4])

In [ ]:
#abs - to find absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negetive
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.2,1.5,2.8,3.4])

In [ ]:
#round
torch.round(d)

tensor([1., 2., 3., 3.])

In [ ]:
#Ceil - for next int goes up
torch.ceil(d)

tensor([2., 2., 3., 4.])

In [ ]:
#floor - for below value goes down
torch.floor(d)

tensor([1., 1., 2., 3.])

In [ ]:
#clamp - in a range you can keep number
torch.clamp(d, min=1, max=2)

tensor([1.2000, 1.5000, 2.0000, 2.0000])

3.reduction operation

In [ ]:
# reduce all numbers to a single number
e = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
e

tensor([[0., 1., 9.],
        [9., 8., 0.]])

In [ ]:
#sum
torch.sum(e)

tensor(27.)

In [ ]:
#Sum along colums
torch.sum(e,dim=0)

tensor([9., 9., 9.])

In [ ]:
#sum along rows
torch.sum(e, dim=1)

tensor([10., 17.])

In [ ]:
#mean
torch.mean(e)

tensor(4.5000)

In [ ]:
#mean along column
torch.mean(e,dim=0)

tensor([4.5000, 4.5000, 4.5000])

In [ ]:
#median
torch.median(e)

tensor(1.)

In [ ]:
#max and min
torch.max(e)

tensor(9.)

In [ ]:
torch.min(e)

tensor(0.)

In [ ]:
#product
torch.prod(e)

tensor(0.)

In [ ]:
#standard diviation
torch.std(e)

tensor(4.5935)

In [ ]:
#variance
torch.var(e)

tensor(21.1000)

In [ ]:
#argmax - shows potion of max
torch.argmax(e)

tensor(2)

In [ ]:
#argminn - shows position of min
torch.argmin(e)

tensor(0)

4. Matric operations

In [ ]:
f = torch.randint(size=(2,3),low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[7, 0, 0],
        [9, 5, 7]])
tensor([[3, 9],
        [4, 0],
        [5, 7]])


In [ ]:
# Matrix multiplication
torch.matmul(f,g)

tensor([[ 21,  63],
        [ 82, 130]])

In [ ]:

vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10,dtype=torch.float32)
h

tensor([[5., 9., 9.],
        [7., 5., 9.],
        [8., 9., 7.]])

In [ ]:
#determinant
torch.det(h)

tensor(184.0000)

In [ ]:
#inverse
torch.inverse(h)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

5.Comparision operations

In [ ]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[9, 2, 6],
        [7, 7, 8]])
tensor([[3, 6, 1],
        [5, 5, 0]])


In [ ]:
#greater than
print("Greater: ",i>j)
print("less than: ", i<j)
print("Equals: ", i==j)
print("Greter than equals: ",i>=j)
print("Less than equals: ",i<=j)


Greater:  tensor([[ True, False,  True],
        [ True,  True,  True]])
less than:  tensor([[False,  True, False],
        [False, False, False]])
Equals:  tensor([[False, False, False],
        [False, False, False]])
Greter than equals:  tensor([[ True, False,  True],
        [ True,  True,  True]])
Less than equals:  tensor([[False,  True, False],
        [False, False, False]])


6.Special funtions

In [ ]:
k = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
k

tensor([[4., 3., 8.],
        [8., 3., 3.]])

In [ ]:
#log
torch.log(k)

tensor([[1.3863, 1.0986, 2.0794],
        [2.0794, 1.0986, 1.0986]])

In [ ]:
#exp - exponents
torch.exp(k)

tensor([[  54.5981,   20.0855, 2980.9580],
        [2980.9580,   20.0855,   20.0855]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[2.0000, 1.7321, 2.8284],
        [2.8284, 1.7321, 1.7321]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9526, 0.9997],
        [0.9997, 0.9526, 0.9526]])

In [ ]:
#softmax
torch.softmax(k, dim=0)

tensor([[0.0180, 0.5000, 0.9933],
        [0.9820, 0.5000, 0.0067]])

In [ ]:
#relu
torch.relu(k)

tensor([[4., 3., 8.],
        [8., 3., 3.]])

Inplace operations

In [ ]:
m= torch.rand(2,3)
n= torch.rand(2,3)

print(m)
print(n)

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])
tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])


In [ ]:
m + n

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
# if you do like this it will take more merory alocation so to make it we will store the ouput value to m
m.add_(n)

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
m

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
n

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])

In [ ]:
torch.relu(m)

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

In [ ]:
m.relu_()

tensor([[0.2624, 1.9251, 1.2663],
        [0.8025, 1.1494, 0.4199]])

Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
b = a #in python to copy this is a common wan b stores value of a
b

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
# if you change the values in a it changes in b also so no meaning of copying there is catch not desirable
a[0][0] = 0
a

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
b

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
# if you check a id of a and b then both shows same location
id(a)

135521598762560

In [ ]:
id(b)

135521598762560

In [ ]:
#so to copy there is a function clone()
a = a.clone()

In [ ]:
a

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
b

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
# both items are same so if i change in a
a[0][0] = 8

In [ ]:
a


tensor([[8.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
b

tensor([[0.0000, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [ ]:
id(a)

135521598903616

In [ ]:
id(b) #so now memery location is different

135521598762560

Tensor operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda') #to store a GPU inn variable called device

In [ ]:
#creating a new tensors on GPU (till now we were creaating on cpu on RAM now on GPU RAM/VRAM) here we have created a new tensor in GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
#moving existing tensors to GPU
a = torch.rand(2,3)
a

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [ ]:
# to move
b = a.to(device)
b

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]], device='cuda:0')

In [ ]:
b + 5 #it performed on GPU

tensor([[5.9141, 5.7668, 5.1659],
        [5.4393, 5.2243, 5.8935]], device='cuda:0')

In [ ]:
#to check speed
import torch
import time

#define the size of th matrices
size = 10000 # large size for performance comparision

# create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size,size)

#measure time on cpu
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time()-start_time

print(f"Time on CPU:{cpu_time:.4f} seconds")

#move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

#measure time on cpu
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize() #ensure all GPU operations are complete
gpu_time = time.time()-start_time

print(f"Time on GPU:{gpu_time:.4f} seconds")

#compare results
print("\n Speedup (CPU time / GPU time)",cpu_time/gpu_time)

Time on CPU:17.5294 seconds
Time on GPU:0.7214 seconds

 Speedup (CPU time / GPU time) 24.29920846332822


Reshaping Tesors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#permute
b = torch.rand(2,3,4)
b


tensor([[[0.7985, 0.4626, 0.9414, 0.5752],
         [0.8881, 0.7989, 0.9514, 0.0141],
         [0.8903, 0.1649, 0.3162, 0.1331]],

        [[0.6763, 0.4254, 0.2375, 0.5430],
         [0.1174, 0.6532, 0.5115, 0.3094],
         [0.7907, 0.7351, 0.2693, 0.8009]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
#unsqueeze - given postion it adds new dimention
c =torch.rand(226,226,3) #image size 226,226,3
c.unsqueeze(0).shape #used in iage classification model

torch.Size([1, 226, 226, 3])

In [ ]:
#squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

NumPy and Pytorch

In [ ]:
#you can covert numpy arrays topytorch tensors and vise varsa

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3])