<a href="https://colab.research.google.com/github/PramodPatil16a/Pytorch-for-AI/blob/main/4_pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the required libraries
import torch
import torch.nn as nn

In [ ]:
#create a model class -
class Model(nn.Module): #class have to inherit from nn.Module to use offerings of nn.Modules
  def __init__(self,Num_features): #constructor

    super().__init__() #invoke custructor of parent class
    self.linear = nn.Linear(Num_features, 1)     #creating Layer(have to pass number of inputs features and output)
    self.sigmoid = nn.Sigmoid() #activation funtion

  #Forward pass
  def forward(self, features):
    #calculate the output when u pass input values to the NN.
    out = self.linear(features) #calulating  Z= wx+b storing in out
    out = self.sigmoid(out)

    return out

In [ ]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for foward pass
model(features) #this is standard way of calling in pytorch instead of #model.forward(features)


tensor([[0.3770],
        [0.3747],
        [0.3657],
        [0.3455],
        [0.3470],
        [0.2884],
        [0.3688],
        [0.3736],
        [0.3664],
        [0.3353]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.1476, -0.2654, -0.2626, -0.0532, -0.1631]], requires_grad=True)

In [ ]:
#show odel bias
model.linear.bias

Parameter containing:
tensor([-0.3074], requires_grad=True)

In [ ]:
# If you want to visualize this network
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00